### ISSUE TITLE
ANSI judge to utf-8

### ISSUE THREAD

**Issue by anonymou3** [JulienPalard/is_utf8#3]
i test utf-8 with bom and utf-8 no bom both windows and linux , they are work fine.  but then i test ansi file include Chinese character get a bad result.   the below content is the ansi file and i save as ansi.txt by notepad++ on windows  :  这明明是ansi怎么判断成了 utf-8了 囧(this is Chinese content)

**Comment by JulienPalard** [comment]
Need feeback.
