### ISSUE TITLE
comment error? 

### ISSUE THREAD

**Issue by carl-wang-cn** [JulienPalard/is_utf8#5]
111110xx 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx
1111110x 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx

this 2 line is not valid utf8 according to RFC 3629

**Comment by JulienPalard** [comment]
You're right I should have read the Unicode standard before writing this stuff ;-) I pushed something more compliant.
