### ISSUE TITLE
return value of is_utf8() should be size_t

### ISSUE THREAD

**Issue by AlbertWiersch** [JulienPalard/is_utf8#7]
Shouldn't the return value of the is_utf8() function be size_t instead of int?

**Comment by JulienPalard** [comment]
Yup, wanna pull request?

**Comment by AlbertWiersch** [comment]
OK, I think I did. This was my first pull request so I had to figure it out… I’m not that familiar with github.

 

Thanks,
Albert Wiersch
AI Internet Solutions LLC
support@htmlvalidator.com
https://www.htmlvalidator.com/

**Comment by JulienPalard** [comment]
Thanks!
